import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PodcastAppProvider } from './context/PodcastAppContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Podcast App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <PodcastAppProvider>
        <body className={inter.className} id='root'>{children}</body>
      </PodcastAppProvider>
    </html>
  )
}
